import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "secondary-container": "var(--color-secondary-container)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-background": "var(--color-on-background)",
        "on-error": "var(--color-on-error)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "error": "var(--color-error)",
        "primary": "var(--color-primary)",
        "on-error-container": "var(--color-on-error-container)",
        "background": "var(--color-background)",
        "outline": "var(--color-outline)",
        "tertiary": "var(--color-tertiary)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "surface": "var(--color-surface)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-secondary": "var(--color-on-secondary)",
        "on-primary": "var(--color-on-primary)",
        "inverse-surface": "var(--color-inverse-surface)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "error-container": "var(--color-error-container)",
        "on-surface": "var(--color-on-surface)",
        "inverse-primary": "var(--color-inverse-primary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "primary-fixed": "var(--color-primary-fixed)",
        "primary-container": "var(--color-primary-container)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "secondary": "var(--color-secondary)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "surface-tint": "var(--color-surface-tint)",
        "on-tertiary": "var(--color-on-tertiary)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-bright": "var(--color-surface-bright)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-primary-container": "var(--color-on-primary-container)",
        "outline-variant": "var(--color-outline-variant)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        "margin-desktop": "48px",
        gutter: "16px",
        "margin-mobile": "16px",
        "container-max": "1280px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-regular": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "data-point": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
        "body-regular": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "data-point": ["20px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};

export default config;
