import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb4aa",
        "secondary-container": "#c3f400",
        "on-surface-variant": "#b9cacb",
        "on-background": "#e5e2e1",
        "on-error": "#690005",
        "tertiary-fixed": "#ffdad5",
        "on-secondary-fixed-variant": "#3c4d00",
        error: "#ffb4ab",
        primary: "#dbfcff",
        "on-error-container": "#ffdad6",
        background: "#131313",
        outline: "#849495",
        tertiary: "#fff3f1",
        "surface-variant": "#353534",
        "surface-container-high": "#2a2a2a",
        "on-tertiary-fixed-variant": "#930005",
        "primary-fixed-dim": "#00dbe9",
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-container-low": "#1c1b1b",
        "on-tertiary-container": "#c1000a",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary": "#283500",
        "on-primary": "#00363a",
        "inverse-surface": "#e5e2e1",
        "on-primary-fixed-variant": "#004f54",
        "error-container": "#93000a",
        "on-surface": "#e5e2e1",
        "inverse-primary": "#006970",
        "tertiary-container": "#ffcec7",
        "primary-fixed": "#7df4ff",
        "primary-container": "#00f0ff",
        "on-primary-fixed": "#002022",
        "inverse-on-surface": "#313030",
        "secondary-fixed-dim": "#abd600",
        "on-tertiary-fixed": "#410001",
        "on-secondary-container": "#556d00",
        secondary: "#ffffff",
        "secondary-fixed": "#c3f400",
        "surface-tint": "#00dbe9",
        "on-tertiary": "#690003",
        "surface-container": "#201f1f",
        "surface-container-highest": "#353534",
        "surface-bright": "#393939",
        "on-secondary-fixed": "#161e00",
        "on-primary-container": "#006970",
        "outline-variant": "#3b494b",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        "margin-desktop": "48px",
        gutter: "16px",
        "margin-mobile": "16px",
        "container-max": "1280px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-regular": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "data-point": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
        "body-regular": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "data-point": ["20px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};

export default config;
